### ISSUE TITLE
Change slider to use up to date API

### ISSUE THREAD

**Issue by aronfiechter** [BalestraPatrick/EmergencyPhoneNumbers#13]
@BalestraPatrick @esposem 
The settings tab needs PreferenceFragment to work properly, which is not compatible with `android.support.v4.app.Fragment*`. I think we need to change the slider so that it uses `android.app.Fragment` and other up to date classes. The problem is that there is not an up to date version of `android.support.v4.app.FragmentStatePagerAdapter` from what I understood. Maybe there are other newer ways to implement the slider view (hopefully, since the Google+, Youtube and many other apps use it).

**Comment by aronfiechter** [comment]
Apparently the slider (`ViewPager`) _has_ to use the support libraries, so I googled a bit more and found that there is a `PreferenceFragmentCompat` library. I got the Settings tab to work but it has still some issues (it opens already over the locations tab and it overlaps the toolbar and everything).

**Comment by BalestraPatrick** [comment]
Can you please push your code so that we can take a look? I think it's fine even if it is still buggy.

**Comment by aronfiechter** [comment]
Found how to make it work, and pushed it. Now it works quite good.
