### ISSUE TITLE
Onboarding screen

### ISSUE THREAD

**Issue by BalestraPatrick** [BalestraPatrick/EmergencyPhoneNumbers#15]
We should quickly onboard users and let them know how to use the app with a fun ActivityView presented the first time. It should also be presented from the Preferences view so that it can be consulted later.

**Comment by aronfiechter** [comment]
Is there already something implemented in Android to do this? Maybe a dedicated library or something like that

**Comment by BalestraPatrick** [comment]
We can find some good open source project for sure.

**Comment by BalestraPatrick** [comment]
A few examples to be considered: 
- https://github.com/chyrta/AndroidOnboarder
- https://github.com/jrejaud/Onboarder
