### ISSUE TITLE
Flags overview tab

### ISSUE THREAD

**Issue by lazy-val** [BalestraPatrick/EmergencyPhoneNumbers#5]
- [x] learn more about Android Studio
- [x] open activity when flag is clicked
- [x] activity with a scrollable list of clickable countries
- [x] close activity if a country is clicked
- [x] remove button flag
- [x] make flag and title clickable
- [x] make a preference fragment out of the scrolling activity

**Comment by aronfiechter** [comment]
Would you agree if we convert the flags scrolling activity into a preference activity so that the selected country can be saved as a string into the settings file? Then it would be easier in general to access the information.
